### ISSUE TITLE
Chapter 6 - FormTextField reference

### ISSUE THREAD

**Issue by cymr0** [PacktPublishing/SwiftUI-Projects#1]
FormTextField is still mentioned in the book, but it was removed in commit 4734057. 

Ignoring this part of the book (page 284-286) and the project still works OK - it's just confusing.

Thought I'd raise this in case anybody else comes across this issue.

**Comment by thedevme** [comment]
Yes it was replaced and I missed this one in the book. FormTextField is now FormNameView.
