### ISSUE TITLE
Chapter 4 - @ObservedObject reference

### ISSUE THREAD

**Issue by neilsheppard** [PacktPublishing/SwiftUI-Projects#2]
Chapter 4 - In the book, the form view section references an ObservedObject, but the starter code and completed code reference an EnvironmentObject.

At the point where you want to preview the form (page 121 / figure 4.11) you have to perform the following.

1. Change the `EnvironmentObject` back to `ObservedObject`
2. Comment / remote `init()`
3. Pass dummy `OrderViewModel()` in the `FormView_Previews` struct

or

1. Keep `EnvironmentObject`
2. Append `.environmentObject(OrderViewModel())` to the `FormView()` in the `FormView_Previews` struct

**Comment by neilsheppard** [comment]
Or keep the `EnvironmentObject` and append `.environmentObject(OrderViewModel())` to the `FormView()` in the `FormView_Previews` struct

**Comment by thedevme** [comment]
Thank you
